version: '3'

services:

  service:
    build: etl
    env_file:
      - .env
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - ./etl/logs:/opt/etl/logs/:rw
      - ./etl/state:/opt/etl/state/:rw
  postgres:
    image: postgres:16
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - .env

  elasticsearch:
    build: es
    environment:
      - discovery.type=single-node
    expose:
      - ${ELASTICSEARCH_PORT}
    env_file:
      - .env
    entrypoint: "elasticsearch && /opt/es/es_index.sh"